version: '3.2'
services:
  vue-ui:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
       - ./:/usr/application/UI
       - /usr/application/UI/node_modules