version: '3.2'
services:
  mocked-backend-server:
    container_name: mocked-backend-server
    restart: always
    image: clue/json-server
    volumes:
      - ./data:/data/
    ports:
      - "5001:80"    

  # vue-ui:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - mocked-backend-server
  #   ports:
  #     - "8080:8080"
  #   container_name: vue-ui
  #   volumes:
  #      - ./:/usr/application/UI
  #      - /usr/application/UI/node_modules